/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linearEquationSystem;

import org.junit.Test;
import static org.junit.Assert.*;

public class GaussTest {
    @Test 
	public void testGaussResult() {
        Gauss gauss = new Gauss(3);
		
		//Assert.assertEquals(
       
    }
}
