/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linearEquationSystem;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

/*import org.junit.Test;
import org.junit.*;
import static org.junit.Assert.*;
*/
public class GaussTest {
    @Test 
	public void testGaussResult() {
		//test with 2 var
        Gauss gauss = new Gauss(2);
		double[][] testMatrix_1 = {{2,1,4},{1,-1,-1}};
		double[] testResult_1 = {1.0,2.0};
		gauss.setMatrix(testMatrix_1);
		gauss.calculate();
		double[] result_2 = gauss.getResult();
		
		//test with 3 var
		gauss = new Gauss(3);
		double[][] testMatrix_2 = {{3,5,1,30},{2,-4,-5,-15},{3,-3,4,1}};
		double[] testResult_2 = {3,4,1};
		gauss.setMatrix(testMatrix_2);
		gauss.calculate();
		double[] result_3 = gauss.getResult();
		
		
		//test with 5 var
		gauss = new Gauss(5);
		double[][] testMatrix_3 = {{3,2,1,4,6,7},{2,-4,-5,3,6,5},{3,-3,4,5,7,8},{2,4,4,5,5,10},{1,-3,-2,5,2,11}};
		double[] testResult_3 = {-0.464,0.150,-0.143,2.422,-0.242};
		gauss.setMatrix(testMatrix_3);
		gauss.calculate();
		double[] result_5 = gauss.getResult();
		//running test for all var
		assertAll("numbers", 
				() -> assertEquals(result_2[0],testResult_1[0],0.001),
				() -> assertEquals(result_2[1],testResult_1[1],0.001),
				() -> assertEquals(result_3[0],testResult_2[0],0.001),
				() -> assertEquals(result_3[1],testResult_2[1],0.001),
				() -> assertEquals(result_3[2],testResult_2[2],0.001),
				() -> assertEquals(result_5[0],testResult_3[0],0.001),
				() -> assertEquals(result_5[1],testResult_3[1],0.001),
				() -> assertEquals(result_5[2],testResult_3[2],0.001),
				() -> assertEquals(result_5[3],testResult_3[3],0.001),
				() -> assertEquals(result_5[4],testResult_3[4],0.001)
				);
		
	
       
    }
	
	
}
